### ISSUE TITLE
Send() doesn't work for big data

### ISSUE THREAD

**Issue by Oscar-Campo** [tomorrowdata/iottly-sdk-python#6]
https://github.com/tomorrowdata/iottly-sdk-python/blob/890a18b7b0edcb812ec74c0260d871937d289df7/iottly_sdk/iottly.py#L445-L453

The sdk.send() doesn't work when the payload is greater than 65535 bytes (TCP packet max size). 

Nothing is sent to the Agent and no exception is raised. sdk.send() stops working.

Probably we need to use [socket.send()](https://docs.python.org/3.7/library/socket.html#socket.socket.send) instead of socket.sendall() and manage the size of payload.

**Comment by baldoalessandro** [comment]
Closing as fixed in upstream https://github.com/tomorrowdata/iottly-device-agent-py/issues/104
